### ISSUE TITLE
Can not get ser/ fold !

### ISSUE THREAD

**Issue by 199843** [Xingwei-Warwick/hyper-event-TempRel#1]
can u upload ser/ fold , the website u given seems not useful .

**Comment by Xingwei-Tan** [comment]
Hi, 

I checked the url. The folder can be downloaded successfully. Is there any restriction blocking you from accessing Amazon's server?

**Comment by 199843** [comment]
Thanks for your reply
I try to use 迅雷 to download the folder, the url can be recognized by 迅雷 but the folder can not be download.
The task connection timed out and the download could not continue

**Comment by 199843** [comment]
Just now , I try again and it works , now I'm downloading the folder ！
